### ISSUE TITLE
Add mirrors support

### ISSUE THREAD

**Issue by NadalVRoMa** [NadalVRoMa/PyLibGen#1]
So libgen.io usually lists 4 mirrors for each book. Right now the script ony downloads from the first mirror. Add support to be able to download from other mirrors

**Comment by saifat29** [comment]
@NadalVRoMa  I want to do it?

**Comment by NadalVRoMa** [comment]
@saifat29 yeah sure, feel free to ask any questions!

**Comment by saifat29** [comment]
@NadalVRoMa This is how I think should be the flow of the newly implemented feature - 

After the user selects a book, we show something as follows-
```
1: Mirror 1
2: Mirror 2
3: Mirror 3
4: Mirror 4
Select a mirror to download from:
```
Is this okay?

**Comment by NadalVRoMa** [comment]
sure! but also add a boolean variable in settings.py that defines if the user wants to have the option to choose a mirror, for the users that want to keep it simple.

**Comment by saifat29** [comment]
@NadalVRoMa Ok, understood.
